### ISSUE TITLE
Not able to build the project using mvn clean install

### ISSUE THREAD

**Issue by manojpant2002** [olensmar/soapui-swagger-plugin#5]
https://github.com/olensmar/soapui-swagger-plugin

C:\Users\testsystem\Desktop\soap\soapui-swagger-plugin-master>mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building SoapUI Swagger plugin 2.1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.smartbear:swagger4j:jar:1.0-beta5 is missing, no dependency information available
[WARNING] The POM for com.smartbear:ready-api-soapui-pro:jar:1.2.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.612s
[INFO] Finished at: Wed Mar 18 09:37:17 IST 2015
[INFO] Final Memory: 5M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project soapui-swagger-plugin: Could not resolve dependencies for project com.smartbear:soapui-swagger-plugin:jar:2.1: The following art
 com.smartbear:swagger4j:jar:1.0-beta5 in http://www.soapui.org/repository/maven2 was cached in the local repository, resolution will not be reattempted until the update
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Can you please check on fresh system,may be dependencies are already there in your build system ,that's why not getting this error.

or can you provide the distribution containing the whiole stuff (jar,extensions.. etc).

**Comment by oombadness** [comment]
This may be a broken dependency as 1.0-beta5 is not in the repo, but 1.0-beta4 is.  You can get past this by updating your POM to look for com.smartbear:swagger4j:jar:1.0-beta4.

http://www.soapui.org/repository/maven2/com/smartbear/swagger4j/1.0-beta4/

**Comment by oombadness** [comment]
PS - https://github.com/SmartBear/swagger4j is the dependency you need if you want to make your own build of the latest.  Note that the version of swagger4j that will be built is 1.0-beta5-SNAPSHOT - so you'll need to alter the POM of swagger4j and remove the -SNAPSHOT or alter the POM of this project to look for -SNAPSHOT.

**Comment by olensmar** [comment]
sorry about this - I've uploaded the beta5 jar to the repo... http://www.soapui.org/repository/maven2/com/smartbear/swagger4j/1.0-beta5/

oombadness - thanks for helping out

/Ole
